security:
  basic:
    enabled: false

spring:
  application:
    name: Office Automation System
  cache:
    cache-names: demo
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60s
    type: caffeine
  redis:
    cluster:
      enabled: N
      max-redirects: 3
      nodes: 127.0.0.1:6379,127.0.0.1:6378,127.0.0.1:6377
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1
    database: 0
    timeout: 0
# 数据库访问配置
# 主数据源，默认的
  datasource:
    druid:
      readwrite:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lufs_preresearch?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        username: root
        password: lufs8888
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
# 配置获取连接等待超时的时间
        maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
      readonly:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lufs_preresearch?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        username: reader
        password: reader8888

# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
# 配置获取连接等待超时的时间
        maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
# 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000

# Merge the monitor data from multiple DruidDataSource
#useGlobalDataSourceStat: true

oas:
  security:
      authentication:
          jwt:
              secret: 6asdsdfsdfse28106e7a2cb36cd
              tokenValidityInSeconds: 3600 # Token is valid 1 hours
  swagger:
      default-include-pattern: /api/.*
      title: Collaborative Automation API
      description: Collaborative Automation  API documentation --- Lufs Co., Inc
      version: 0.0.1
      terms-of-service-url:
      contact-name:
      contact-url:
      contact-email:
      license:
      license-url:

dingtalk:
  env:
    open-api-host: https://oapi.dingtalk.com
    oas-bg-url: https://oapi.dingtalk.com
    corp-id: dingd0df05d01dc3d02635c2f4657eb6378f
    corp-secret: hFNEHMkslzVMSvikCa5w23y82lZ9fUtEJ864-rtfRw14vl5l8cX2Lhu0yZAkvyPR
    sso-secret:
    suite-ticket:
    suite-token:
    suite-secret:
    suite-key:
    craete-suite-key: suite4xxxxxxxxxxxxxxx
    token:
    encoding-aes-key:
    auth-token:
    agent-id: 124949289
    cache-time: 6600
